### ISSUE TITLE
Eureka-ROM EOL'ed December 2015

### ISSUE THREAD

**Issue by BenjaminHCCarr** [team-eureka/Eureka-ROM#10]
http://forum.xda-developers.com/android-tv/chromecast/rom-flashcast-autoroot-t3270332

Team Eureka has moved to [ROM] Flashcast-AutoRoot, with ssh, adb, and OTA w/ root support

**Comment by riptidewave93** [comment]
Merged your PR at https://github.com/team-eureka/Eureka-ROM/pull/11, marking as resolved.
